AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  image-recognizer-serverless
  Sample SAM Template for image-recognizer-serverless

Parameters:
  Environment:
    Type: String
  ImagesBucketName:
    Type: String
    Default: "image-recognizer-images-bucket"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    CodeUri: app/
    Environment:
      Variables:
        environment: !Ref Environment
        imagesBucketName: !Ref ImagesBucketName

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
  ImagesBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref ImagesBucketName
  ImagesBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref ImagesBucketName
      PolicyDocument:
        Statement:
          - Sid: PublicReadForPutBucketObjects
            Effect: Allow
            Principal: "*" # Anyone
            Action:
              - "s3:PutObject"
            Resource:
              - !Sub "arn:aws:s3:::${ImagesBucketName}"
              - !Sub "arn:aws:s3:::${ImagesBucketName}/*"
  GeneratePreSignedUrlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.generatePreSignedUrl
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recognizer/upload-url
            Method: POST
            RestApiId: !Ref ApiGatewayApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020" # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Hello World function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/hello"

  RandomNumbersApi:
    Description: "API Gateway endpoint URL for Random Numbers function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/random"
